version: '3.8'

services:
  db:
    image: smithcastellanos/casacafe-db:latest
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casacafe
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: smithcastellanos/casacafe-phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  web:
    image: smithcastellanos/casacafe-web:latest
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - db
